# Generated by Django 4.2 on 2023-04-27 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stonks", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="swiftnessdeposit",
            name="swiftness_deposit_primary_key",
        ),
        migrations.AddConstraint(
            model_name="swiftnessdeposit",
            constraint=models.UniqueConstraint(
                fields=(
                    "product_type",
                    "managing_company",
                    "policy_id",
                    "value_date",
                    "wage_month",
                    "user_id",
                ),
                name="swiftness_deposit_primary_key",
            ),
        ),
    ]
