# Generated by Django 4.2 on 2023-04-29 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "stonks",
            "0002_remove_swiftnessdeposit_swiftness_deposit_primary_key_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="BankTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_num", models.TextField()),
                ("txn_id", models.TextField()),
                ("time", models.DateTimeField()),
                ("amount", models.FloatField()),
                ("description", models.TextField()),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BankState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_num", models.TextField()),
                ("time", models.DateTimeField()),
                ("balance", models.FloatField()),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="banktransaction",
            constraint=models.UniqueConstraint(
                fields=("txn_id", "account_num", "user_id"),
                name="bank_transaction_primary_key",
            ),
        ),
        migrations.AddConstraint(
            model_name="bankstate",
            constraint=models.UniqueConstraint(
                fields=("time", "account_num", "user_id"), name="bank_state_primary_key"
            ),
        ),
    ]
