{
 "title": "גמל",
 "time": { "from": "now/y", "to": "now/y" },
 "panels": [
  { "title": "לאורך זמן", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "סיכום קופות",
   "type": "timeseries",
   "gridPos": { "h": 31, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "suffix:₪" } },
   "targets": [
    {
     "queryText": "WITH my_products AS (SELECT * from stonks_swiftnessproduct WHERE user_id_id = 1)\nSELECT format(\"%sT00:00:00Z\", date_of_validity) as date, product_name as name, total_savings as value\nFROM my_products\nWHERE total_savings > 0\nORDER BY date_of_validity ASC, total_savings ASC;\n",
     "rawQueryText": "WITH my_products AS (SELECT * from stonks_swiftnessproduct WHERE user_id_id = 1)\nSELECT format(\"%sT00:00:00Z\", date_of_validity) as date, product_name as name, total_savings as value\nFROM my_products\nWHERE total_savings > 0\nORDER BY date_of_validity ASC, total_savings ASC;\n",
     "timeColumns": [ "date" ]
    }
   ]
  },
  {
   "title": "קופת גמל להשקעה",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "suffix:₪" } },
   "targets": [
    {
     "queryText": "WITH my_products AS (SELECT * from stonks_swiftnessproduct WHERE user_id_id = 1)\nSELECT format('%sT00:00:00Z', date_of_validity) as date, total_savings as value\nFROM my_products\nWHERE total_savings > 0 AND managing_company = 'הפניקס פנסיה וגמל בע\"מ' AND product_name = 'קופת גמל להשקעה'\nORDER BY date_of_validity ASC;\n",
     "rawQueryText": "WITH my_products AS (SELECT * from stonks_swiftnessproduct WHERE user_id_id = 1)\nSELECT format('%sT00:00:00Z', date_of_validity) as date, total_savings as value\nFROM my_products\nWHERE total_savings > 0 AND managing_company = 'הפניקס פנסיה וגמל בע\"מ' AND product_name = 'קופת גמל להשקעה'\nORDER BY date_of_validity ASC;\n",
     "timeColumns": [ "date" ]
    }
   ]
  },
  { "title": "הפקדות", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "הפקדות",
   "type": "table",
   "gridPos": { "h": 20, "w": 9, "x": 0, "y": 33 },
   "targets": [
    {
     "queryText": "WITH my_deposits AS (SELECT * from stonks_swiftnessdeposit WHERE user_id_id = 1)\nSELECT SUM(job_deposits_for_compensation) AS job_deposits_for_compensation,\n       SUM(job_deposits) AS job_deposits,\n       SUM(personal_deposits) AS personal_deposits,\n       format('%s [%s]', product_type, managing_company) AS name,\n        strftime('%Y-%m-%d', value_date) AS value_date\nFROM my_deposits\nGROUP BY value_date, managing_company, product_type\nORDER BY value_date DESC, managing_company ASC, product_type ASC;",
     "rawQueryText": "WITH my_deposits AS (SELECT * from stonks_swiftnessdeposit WHERE user_id_id = 1)\nSELECT SUM(job_deposits_for_compensation) AS job_deposits_for_compensation,\n       SUM(job_deposits) AS job_deposits,\n       SUM(personal_deposits) AS personal_deposits,\n       format('%s [%s]', product_type, managing_company) AS name,\n        strftime('%Y-%m-%d', value_date) AS value_date\nFROM my_deposits\nGROUP BY value_date, managing_company, product_type\nORDER BY value_date DESC, managing_company ASC, product_type ASC;"
    }
   ]
  }
 ]
}